CREATE TABLE author (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(30) NOT NULL,
    surname character varying(30) NOT NULL
);

CREATE TABLE news (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title character varying(30) NOT NULL,
    short_text character varying(100) NOT NULL,
    full_text character varying(2000) NOT NULL,
    creation_date date NOT NULL,
    modification_date date NOT NULL
);

CREATE TABLE tag (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying (30) NOT NULL
);

CREATE TABLE user_account (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(20) NOT NULL,
    surname character varying(20) NOT NULL,
    username character varying(30) NOT NULL,
    password character varying(100) NOT NULL
);

CREATE TABLE user_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(30) NOT NULL
);

CREATE TABLE client (
    id character varying(30) PRIMARY KEY,
    secret character varying(100) NOT NULL,
    grant_type character varying(20) NOT NULL
);

CREATE TABLE news_author (
    author_id bigint NOT NULL,
    news_id bigint NOT NULL,
    FOREIGN KEY (author_id) REFERENCES author (id),
    FOREIGN KEY (news_id) REFERENCES news (id)
);

CREATE TABLE news_tag (
    news_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    FOREIGN KEY (tag_id) REFERENCES tag (id),
    FOREIGN KEY (news_id) REFERENCES news (id)
);

CREATE TABLE users_and_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user_account (id),
    FOREIGN KEY (role_id) REFERENCES user_role (id)
);